kind: pipeline
name: default

steps:
- name: Build drone-gke
  image: golang
  commands:
    - make drone-gke

- name: Build and push docker image
  image: plugins/docker
  settings:
    repo: docker.pliro.enlyze.com/enlyze/drone-sops-gke
    cache_from: docker.pliro.enlyze.com/enlyze/drone-sops-gke
    auto_tag: true
    custom_dns: 10.20.191.1
