kind: pipeline
name: default

steps:
- name: Build drone-gke
  image: golang
  commands:
    - make drone-gke

- name: Build and push docker image
  image: plugins/docker
  settings:
    registry: docker.pliro.enlyze.com
    repo: enlyze/drone-sops-gke
    auto_tag: true
    custom_dns: 10.20.191.1
    build_args:
      - GCLOUD_SDK_TAG=alpine
